### ISSUE TITLE
Variable BEM-like naming convention

### ISSUE THREAD

**Issue by ncoden** [lewattman/sass-conventions#1]
Use an BEM naming for variables too:
- `__` for sub-property
- `--` for modifier

Example: see https://github.com/ncoden/caliopen.web-client-ng/blob/master/src/styles/base/_colors.scss

**Comment by gabrielnau** [comment]
Hi,

Thanks for proposing an improvement ! But this repository isn't active since 2-3 years, it could be closed actually. There is probably tons of other styleguide up to date with modern practices.

**Comment by ncoden** [comment]
:ok_hand:
